feat(index): add willBeCouple var
wonderlanded/saidbysolo pull request #1
Opened 2021-03-03 14:44 UTC by SaidBySolo

2021-03-03 14:45 UTC, wonderlandpark commented
Missing typing

2021-03-03 14:45 UTC, wonderlandpark requested changes

2021-03-03 14:45 UTC, wonderlandpark commented on index.js
> +  willBeCouple: true,
```suggestion
  willBeCouple: false,
```

2021-03-03 14:47 UTC, SaidBySolo commented on index.js
> +  willBeCouple: true,
why false?

2021-03-25 13:39 UTC, wonderlandpark requested changes

2021-03-25 13:39 UTC, wonderlandpark commented on index.js
> +  willBeCouple: true,
Conflict with https://github.com/wonderlandpark/saidbysolo/blob/3212ce9e4289760e281aacba369883300a062ce1/index.js#L5

2021-07-13 19:47 UTC, closed without merging